<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCWZpbGVuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJmaWxlbmFtZSIgKTsNCglTdHJpbmcJbG9hZEFzID0gSURhdGFVdGlsLmdldFN0cmlu
ZyggcGlwZWxpbmVDdXJzb3IsICJsb2FkQXMiICk7DQoJU3RyaW5nIGRhdGEgPSBudWxsOw0KCU9i
amVjdCBieXRlcyA9IG5ldyBPYmplY3QoKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCi8v
IHBpcGVsaW5lDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpGaWxlIGZpbGUgPSBuZXcgRmlsZShmaWxlbmFtZSk7DQoNCnRyeSB7DQoJCWlmIChs
b2FkQXMuY29udGFpbnMoImJ5dGVzIikpew0KCQlieXRlcyA9IEZpbGVVdGlscy5yZWFkRmlsZVRv
Qnl0ZUFycmF5KGZpbGUpOw0KCQlJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAiYnl0
ZXMiLCBieXRlcyApOw0KCQl9DQoJCWVsc2V7DQoJCWRhdGEgPSBGaWxlVXRpbHMucmVhZEZpbGVU
b1N0cmluZyhmaWxlLCAiVVRGLTgiKTsgDQoJCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29y
XzEsICJzdHJpbmciLCBkYXRhICk7DQoJCX0JCQ0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgew0K
CS8vIFRPRE8gQXV0by1nZW5lcmF0ZWQgY2F0Y2ggYmxvY2sNCgllLnByaW50U3RhY2tUcmFjZSgp
Ow0KfQ0KDQoNCg0KcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7DQoJ</value>
</Values>
