<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">existsService</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCg0KDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOw0KdHJ5IHsNCglTdHJpbmcJc2VydmljZU5hbWUgPSBJRGF0YVV0aWwuZ2V0U3Ry
aW5nKCBwaXBlbGluZUN1cnNvciwgInNlcnZpY2VOYW1lIiApOw0KCQ0KCS8vIERlZmF1bHQgcmV0
dXJuIHZhbHVlIGlzIGZhbHNlDQoJYm9vbGVhbiBleGlzdHNTZXJ2aWNlID0gZmFsc2U7DQoJDQoJ
Ly8gQ2hhbmdlIHJldHVybiB2YWx1ZSBpZiBub2RlIGV4aXN0cyBhbmQgaXMgb2YgdHlwZSBzZXJ2
aWNlDQoJTlNOb2RlIG5vZGUgPSBOYW1lc3BhY2UuY3VycmVudCgpLmdldE5vZGUoc2VydmljZU5h
bWUpOw0KCWlmIChub2RlICE9IG51bGwpIHsNCgkJTlNUeXBlIHR5cGUgPSBub2RlLmdldE5vZGVU
eXBlT2JqKCk7DQoJCWlmICh0eXBlLmVxdWFscyhOU1NlcnZpY2UuVFlQRSkpIHsNCgkJCWV4aXN0
c1NlcnZpY2UgPSB0cnVlOw0KCQl9DQoJfQ0KCQ0KCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vy
c29yLCAiZXhpc3RzU2VydmljZSIsICIiICsgZXhpc3RzU2VydmljZSApOw0KfSBmaW5hbGx5IHsN
CglwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQp9DQoNCg0KDQoNCgk=</value>
</Values>
