<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deleteFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCWZpbGVOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJmaWxlTmFtZSIgKTsNCglTdHJpbmcJaXNGb2xkZXIgPSBJRGF0YVV0aWwuZ2V0U3Ry
aW5nKCBwaXBlbGluZUN1cnNvciwgImlzRm9sZGVyIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJv
eSgpOw0KU3RyaW5nIG1lc3NhZ2U9IiI7DQpGaWxlIGZpbGUgPSBuZXcgRmlsZShmaWxlTmFtZSk7
DQppZihpc0ZvbGRlci5jb250YWlucygidHJ1ZSIpKXsNCglkZWxldGVEaXJlY3RvcnkoZmlsZSk7
DQp9DQoNCglpZiAoZmlsZS5kZWxldGUoKSkgew0KCSAgICBtZXNzYWdlPSJzdWNjZXNzIjsNCgl9
DQoJZWxzZSB7DQoJCW1lc3NhZ2U9IkVycm9yLiBVbmFibGUgZGVsZXRlIHRoZSBmaWxlIjsNCgl9
DQoNCi8vIHBpcGVsaW5lDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUu
Z2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAibWVzc2FnZSIs
IG1lc3NhZ2UgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0KDQoJ</value>
</Values>
