<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listDirectories</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCWRpcmVjdG9yeSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5l
Q3Vyc29yLCAiZGlyZWN0b3J5IiApOw0KCQ0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpG
aWxlW10gZGlyZWN0b3JpZXMgPSBuZXcgRmlsZShkaXJlY3RvcnkpLmxpc3RGaWxlcyhGaWxlOjpp
c0RpcmVjdG9yeSk7DQoNClN0cmluZ1tdIGRpcmVjdG9yeU5hbWVzID0gbmV3IFN0cmluZ1tkaXJl
Y3Rvcmllcy5sZW5ndGhdOw0KZm9yIChpbnQgaSA9IDA7IGkgPCBkaXJlY3Rvcmllcy5sZW5ndGg7
IGkrKykgew0KCWRpcmVjdG9yeU5hbWVzW2ldID0gZGlyZWN0b3JpZXNbaV0uZ2V0TmFtZSgpOw0K
fQ0KDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5l
LmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImRpcmVjdG9y
eU5hbWVzIiwgZGlyZWN0b3J5TmFtZXMgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw==
</value>
</Values>
